version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www/html
    environment:
      - APP_DEBUG=true
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
    build:
      context: .
      dockerfile: Dockerfile.dev

  nginx:
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/app.local.conf:/etc/nginx/conf.d/app.conf

  mysql:
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
